dataset: {
  dataset_root_dir: '/home/yinhuiwang/EEG/data',
  train_data_path: 'dataset/train',
  train_label_path: 'dataset/label/triple_label.npy',
}
EEG_net: { 
  kernLength: 256, 
  dropoutRate: 0.25, 
  F1: 4, 
  D: 2, 
  norm_rate: 0.25,
  alpha: 0.1,
  learning_rate: 0.001,
  num_classes: 3,
}
trainer: {
  max_epochs: 60,
  auto_lr_find: False,
  accelerator: 'gpu',
  devices: 2
}
save_ckpt_path: 'new_weights.pth'
